cookie:
  expiry_days: 30
  key: a_secret_key
  name: freediving_cookie
credentials:
  usernames:
    alaink:
      email: alaink@example.com
      name: Alain K.
      password: $2b$12$45RLvrHyG3pOvBZqpWJGhOCuW8MDO99OSB5f.aGkpsWLYz6.ns3wu
    arnaudb:
      email: arnaudb@example.com
      name: Arnaud B.
      password: $2b$12$fU.lK72LED8Lb3BLmYgk.uqBZicd9WLXAnDyk3u5JuyOL7Yv03C6a
    aurelieb:
      email: "aur\xE9lieb@example.com"
      name: "Aurélie B."
      password: $2b$12$CkIUS/HOD10wCl9UCv50juIVsq2VK3P6XssU4ArHWSQCKqlXQF7KC
    bernardvh:
      email: bernardvh@example.com
      name: Bernard V.H.
      password: $2b$12$/9Bk46O3/1BcpueBBabH.eD45Nsyd59e7Re3Cl/MKBYhB4Yb87qY6
    charlesd:
      email: charlesd@example.com
      name: Charles D.
      password: $2b$12$Z3rsmW14bLNVtdtzq75lAOhmWoC/iGDQzrsvuVaUqsllbm1f2op7G
    charlesdb:
      email: charlesdb@example.com
      name: Charles D.B.
      password: $2b$12$MbjO.0qN3WLKOYoJ3hNSv.3Bm.EeDxYbAOYKwgCv65tVn8JzTnX/m
    charlesdt:
      email: charlesdt@example.com
      name: Charles D.T.
      password: $2b$12$fTeb4LSICbkhGyJCzlJO/O653NLio5Y6TcreSxqjdYno9INwd2MOG
    donalds:
      email: donalds@example.com
      name: Donald S.
      password: $2b$12$amb0vTwJmXuoKdXL6vN/f.qcV0k8JZZ6VjN.ploZhKhN3lkWZwEee
    deborrahl:
      email: "déborahl@example.com"
      name: "Deborrah L."
      password: $2b$12$K3Wt8CMIT557JB8GICxTXuCGFE1h47LTcYEO.j78CN72dPyjWGzeW
    emmanuelh:
      email: emmanuelh@example.com
      name: Emmanuel H.
      password: $2b$12$nHa2LtUSROBwIyY1qj4SxeygLXXh/GgbkQInpbZ70FoTqyHeCo2xG
    ericm:
      email: ericm@example.com
      name: Eric M.
      password: $2b$12$K8pwgwvVLTwGYXqyz8HXhOfZkvL2345hEMdhmStsF008FjscYGHKq
    florences:
      email: florences@example.com
      name: Florence S.
      password: $2b$12$q9l9a3NVyNnZUvDpeaTJo.H.GkiM7pmF9gqrkewvWNVkC6Vvo3JNW
    francoisb:
      email: "fran\xE7oisb@example.com"
      name: "François B."
      password: $2b$12$NsKwU3qFYfZvBj1M6NOnCO9Jcww/FL88eZSXEqsJ0zhNbOSt5dcbG
    gregoryd:
      email: gregoryd@example.com
      name: Gregory D.
      password: $2b$12$1RCmRSPceRIQnVaRu3e0Eu1Dk/m3HF5QpBOp9S/LisJuXA0SznzGG
    gregoirel:
      email: "gr\xE9goirel@example.com"
      name: "Gréggoire L."
      password: $2b$12$9wHfwrmErNiIgwQHc3Xkp.jyWi3jBJYrBfu0IkMZfF5SRt2rytERG
    laurannep:
      email: laurannep@example.com
      name: Lauranne P.
      password: $2b$12$nxAYmzgJGq6qPpWUfGw24e0uhh4D717vSE0/STIyc3TPHZz4uc3Ku
    lucd:
      email: lucd@example.com
      name: Luc D.
      password: $2b$12$4N279D0kGiWXZNsEtKv5vetJE33imZZ5TiOm9Q6hQ8r3wgVO/6V66
    martinv:
      email: martinv@example.com
      name: Martin V.
      password: $2b$12$dCu6V3twyZ7Ggdz/q4a6KuYp/2E6IqMbC9x13cM.6aWzGhsAXM5nm
    michelf:
      email: michelf@example.com
      name: Michel F.
      password: $2b$12$G6CyfMxTtwioWhCW7xQEkuo.NmT6VXcc71.cXnOLPkOj2yZTQlIZu
    perrinem:
      email: perrinem@example.com
      name: Perrine M.
      password: $2b$12$rTRiT5qAkvV5w6tfFsXQvulr8yHe6QbiNhsJV9H06F3EjnQhOuAt6
    philipped:
      email: philipped@example.com
      name: Philippe D.
      password: $2b$12$/AD7tzTrzXf4Qp4L8IXZQ.2BW.xI.wN2vsMnUiZ2AoEMBYQEgYSsi
    philippek:
      email: philippek@example.com
      name: Philippe K.
      password: $2b$12$T1T9PZh62HYQclZbSuRJTuDAyB3WmDC8GVhsj0pVoLlVhVRr7QuUC
    remyl:
      email: "r\xE9myl@example.com"
      name: "Rémy L."
      password: $2b$12$t5CEUCYOxuz58.2AjKwDZOrAuHYBIulnPfI76qvQMtI44xJU2Nlp6
    stephaned:
      email: "st\xE9phaned@example.com"
      name: "Stéphane D."
      password: $2b$12$nHa2LtUSROBwIyY1qj4SxeygLXXh/GgbkQInpbZ70FoTqyHeCo2xG
    sebastienl:
      email: "s\xE9bastienl@example.com"
      name: "Sébastien L."
      password: $2b$12$slTMpHazjitUOwgz60jj7.AsKdD4vvR89/i5asRLt5CzDD2X6fNXC
    theog:
      email: "th\xE9og@example.com"
      name: "Théo G."
      password: $2b$12$CcqXVQIfqTArau2RBhNAmu1LevFzxNUuSWPW9/w2Bx49JVymuumgm
    vincentc:
      email: vincentc@example.com
      name: Vincent C.
      password: $2b$12$.SqG3g0ZctDK7j7LwUdjju.ea6udfC.slZ6ElC85z/vsAURXKpCXS
    xavierh:
      email: xavierh@example.com
      name: Xavier H.
      password: $2b$12$nHa2LtUSROBwIyY1qj4SxeygLXXh/GgbkQInpbZ70FoTqyHeCo2xG
    xavierm:
      email: xavierm@example.com
      name: Xavier M.
      password: $2b$12$/7Xg8ZCmdVIdtRJbo.Dm8uLbBVNZEufO5vOZ0YJAa/zY8d3m/GRru
    yvesg:
      email: yvesg@example.com
      name: Yves G.
      password: $2b$12$8LNNHGeoLfJ.sH3m9T5Ny.KJ15GwcZo1k57kr685lAUWwNNdO0/N.
