cookie:
  expiry_days: 30
  key: a_secret_key
  name: freediving_cookie
credentials:
  usernames:
    alaink:
      email: alaink@example.com
      name: Alain K.
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    arnaudb:
      email: arnaudb@example.com
      name: Arnaud B.
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    "aur\xE9lieb":
      email: "aur\xE9lieb@example.com"
      name: "Aur\xE9lie B."
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    bernardvh:
      email: bernardvh@example.com
      name: Bernard V.H.
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    charlesd:
      email: charlesd@example.com
      name: Charles D.
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    charlesdb:
      email: charlesdb@example.com
      name: Charles D.B.
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    charlesdt:
      email: charlesdt@example.com
      name: Charles D.T.
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    donalds:
      email: donalds@example.com
      name: Donald S.
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    "d\xE9borahl":
      email: "d\xE9borahl@example.com"
      name: "D\xE9borah L."
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    emmanuelh:
      email: emmanuelh@example.com
      name: Emmanuel H.
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    ericm:
      email: ericm@example.com
      name: Eric M.
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    florences:
      email: florences@example.com
      name: Florence S.
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    "fran\xE7oisb":
      email: "fran\xE7oisb@example.com"
      name: "Fran\xE7ois B."
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    gregoryd:
      email: gregoryd@example.com
      name: Gregory D.
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    "gr\xE9goirel":
      email: "gr\xE9goirel@example.com"
      name: "Gr\xE9goire L."
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    laurannep:
      email: laurannep@example.com
      name: Lauranne P.
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    lucd:
      email: lucd@example.com
      name: Luc D.
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    martinv:
      email: martinv@example.com
      name: Martin V.
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    michelf:
      email: michelf@example.com
      name: Michel F.
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    perrinem:
      email: perrinem@example.com
      name: Perrine M.
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    philipped:
      email: philipped@example.com
      name: Philippe D.
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    philippek:
      email: philippek@example.com
      name: Philippe K.
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    "r\xE9myl":
      email: "r\xE9myl@example.com"
      name: "R\xE9my L."
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    "st\xE9phaned":
      email: "st\xE9phaned@example.com"
      name: "St\xE9phane D."
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    "s\xE9bastienl":
      email: "s\xE9bastienl@example.com"
      name: "S\xE9bastien L."
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    "th\xE9og":
      email: "th\xE9og@example.com"
      name: "Th\xE9o G."
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    vincentc:
      email: vincentc@example.com
      name: Vincent C.
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    xavierh:
      email: xavierh@example.com
      name: Xavier H.
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    xavierm:
      email: xavierm@example.com
      name: Xavier M.
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
    yvesg:
      email: yvesg@example.com
      name: Yves G.
      password: $2b$12$swHDz7yXjk0yQhVrHdEohOPbnCTQmjBcoqIAoZFNhjtXE137XX4fO
